### ISSUE TITLE
Change uint to uint256?

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#10]
* https://github.com/OpenZeppelin/openzeppelin-solidity/issues/226
* https://ethereum.stackexchange.com/questions/43241/why-write-uint256-instead-of-uint-if-theyre-the-same-thing

Reading the code, made me think...

**Comment by clesaege** [comment]
It's a matter of personal preference. Specifying more or being more concise both have their pros and cons.

I think the important is to choose one and stick to it but both are equally valid.
