### ISSUE TITLE
Time. Withdraw. Refund. 1s difference. Inconsistent output.

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#14]
Love you guys and really want to help.

I'm following the tokensale schedule described in the blog post: https://medium.com/kleros/how-interactive-coin-offerings-iicos-work-beed401ce526

I'm worried that I add the time, calculate the withdraw, but there is `1s` difference that makes the test fail.

```
 increaseTime: addSeconds => {
   web3.currentProvider.send({jsonrpc: "2.0", method: "evm_increaseTime", params: [addSeconds], id: 0})
 },
```

4 consecutive runs. **Pass. Fail. Fail. Pass.** Could be some sub-second differences.

Video illustrating the issues, speeded up 4 times: https://youtu.be/cF8r0Vq4IJ8

See the full output log: https://pastebin.com/K8DznJ7Z

Added some Events in the `IICO.js` for debugging purposes.

Code in my branch: https://github.com/stefek99/openiico-contract/blob/blog-test-case/test/blog.js

**Comment by clesaege** [comment]
There is some time before a transaction is mined, so the test cannot be strict but give a result in a specific internal taking into account the time to be mined.

**Comment by stefek99** [comment]
Okay, I see.

The results of the tests should have some tolerance.

```
assert(buyerBBalanceAfterReimbursment.minus(buyerBBalanceBeforeReimbursment.minus(txFee).toNumber()).toNumber()-4*0.1E18/5 <= (4*0.1E18/5)/100, 'The buyer has not been reimbursed correctly') // Allow up to 1% error due to time taken outside of increaseTime.
 ```

Of course.

Thank you for clarifying :)

**Comment by stefek99** [comment]
Truffle is using `Mocha` and `Chai`: http://truffleframework.com/docs/getting_started/javascript-tests

`Chai` offers: http://www.chaijs.com/api/assert/

`assert.closeTo(1.5, 1, 0.5, 'numbers are close');`

In the code:

`assert.closeTo(CarlBalanceBeforeReimbursment.plus(1E18).minus(txFee).toNumber(), CarlBalanceAfterReimbursment.toNumber(), 0.005*1E18, 'Reimbursement amount not correct');`
