### ISSUE TITLE
Rename maxVal to maxValuation - otherwise "value" and "valuation" are confusing.

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#17]
FYI - not trying to piss you off with nitty-gritty details but chances are this code will become a new standard so we can ensure proper naming conventions hell yeah...

**Comment by clesaege** [comment]
Yes, feel free to make a PR to do so.

**Comment by stefek99** [comment]
Boom: https://github.com/kleros/openiico-contract/pull/21/files

Mass renames, easy job.
