### ISSUE TITLE
Automated withdrawals? Kicking out from the sale? Inconsistency with the blog...

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#18]
I'm writing the test case for the blog example: https://medium.com/kleros/how-interactive-coin-offerings-iicos-work-beed401ce526

> In this phase, automatic withdrawals start taking place on every block. 

> In the next block, Bob will be kicked out of the sale, the valuation will be at 14 ETH and Bob will be refunded at the end of the sale.

----

### What users are doing

1. Alice puts: 6 ETH, no cap
2. Bob puts: 10 ETH, 20 ETH cap
3. Carl puts: 5 ETH, 25 ETH cap (and withdraws 1)
4. David puts: 4 ETH, 24 ETH cap

### What code is doing

As we finalise the IICO, we start from:
1) Alice, no cap, now the sum is 6 ETH
2) Carl, 25 ETH, now the sum is 10 ETH (give or take 1s mismatch when the refund happened)
3) David, 24 ETH, now the sum is 14 ETH
4) Bob, 20 ETH...

https://github.com/kleros/openiico-contract/blob/master/contracts/IICO.sol#L210-L218

So in the current implementation of the code, Bob contributes 6 ETH, see `CutOff` event...

```
    Finalizing(id: 1, sum: 0, virtual: 0)
    Finalizing(id: 3, sum: 6000000000000000000, virtual: 7200000000000000000)
    Finalizing(id: 4, sum: 10004000000000000000, virtual: 11444133225332000000)
    Finalizing(id: 2, sum: 14004000000000000000, virtual: 15763813225332000000)
    CutOff(howmuch: 5996000000000000000)
    Finalize(id: 2, eth: 20000000000000000000, virtual: 22898813385332000000)
```

Added plenty of events to my branch to debug the thing: https://github.com/stefek99/openiico-contract/blob/blog-test-case/test/blog.js

---

Not easy to explain all the intricacies using plain text... Any questions ping me tomorrow in the morning.

**Comment by epiqueras** [comment]
Yes, we chose to implement partial automatic withdrawals instead.

You could make a case for both options.

**Comment by stefek99** [comment]
The blog remains inconsistent with the code... Bob with `20 ETH maxValuation` contributes` 6 ETH` so that his `maxValuation` is reached?

Note #17 - using `maxValuation` for clarity.

**Comment by epiqueras** [comment]
The blog post explains the mechanics of an IICO in general, both are valid implementations. I added a footnote for clarity.

>**Note that an implementation would still be valid if the “kick out” was only partial. E.g. Bob got a 4 ETH refund, but 6 ETH remained in the sale to meet his personal cap of 20 ETH.
