### ISSUE TITLE
Make a stress test on the finalize

### ISSUE THREAD

**Issue by clesaege** [kleros/openiico-contract#26]
Make a test with an amount of bids such that one call of finalize function would take more than the block gas limit and verify it can finalize in multiple finalize calls.
This test must be in a file apart if it takes a significant amount of time to execute (it may).

**Comment by stefek99** [comment]
In case someone is wondering how to run tests with more than 10 accounts: https://ethereum.stackexchange.com/questions/48413/truffle-test-how-to-get-more-than-10-accounts/48417
