### ISSUE TITLE
⚠️⚠️⚠️function valuationAndCutOff() does not return anything ⚠️⚠️⚠️

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#28]
`function valuationAndCutOff() public view returns (uint valuation, uint virtualValuation, uint currentCutOffBidID, uint currentCutOffBidmaxValuation, uint currentCutOffBidContrib) {`

Where is the return statement in the code?

Is it intentional to have the function that `returns` and then nothing...

HMMM...

https://github.com/kleros/openiico-contract/blob/master/contracts/IICO.sol#L323-L346

**Comment by epiqueras** [comment]
Returns don't have to be explicit.

See https://ethereum.stackexchange.com/questions/34046/what-is-the-purpose-of-giving-name-to-return-variables-in-function-declaration.

**Comment by stefek99** [comment]
Syntactic sugar of Solidity.

In my opinion, can cause more harm than good.

Explicit return is better.

**Comment by stefek99** [comment]
### 1 line only:
`modifier onlyOwner{ require(owner == msg.sender); _; }`

### 53 lines:
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/ownership/Ownable.sol

I really enjoy the concise code 👍
