### ISSUE TITLE
IICO should not accept bids with maxValuation lower than the amount of already submitted ETH

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#31]

**Comment by stefek99** [comment]
But...

The valuation is known after the `finalize`.

So when someone sends `100000 ether` at `1 wei` valuation...

These are small details, mostly around common sense and input sanitization.

**Comment by clesaege** [comment]
Well people can withdraw their bids, so you may still want to submit bids at a valuation lower than the current one.
And even if it was not possible, this should be dealt at the UI level not the smart contract one. The smart contracts must prevent malicious behaviour, the UI must prevent the stupid ones.

**Comment by clesaege** [comment]
Yes sir: https://twitter.com/clesaege/status/1001520815693844480 :p
