### ISSUE TITLE
Align incentives for IICO participants by offering affiliate referral commission baked into the smart contract

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#32]
### "old style" ICO

The more people participate, the more hype, the better for me.

### IICO

I want my `1 ether` to give me the most amount of tokens.

I do not have incentives for promoting the sale, otherwise `1 ether` gives me less tokens.

---

Allow users to register their nickame.

In sale front-end allow field for referral.

To incentivise use of front-end over sending ETH via fallback payable:
* put a referral, get 2% extra each
* leave referral empty, get 1% extra

There could be some multi-level referral bonuses too.

They would be calculated during finalize / redeem phase.

Totally not use about gas usage (amount of lookups and efficient data structures), more concerned about the right incentives - so that poeple investing ETH into sale had incentives to promote the project.

After all the goal of the core team is to raise enough fund to allow for continous development.

**Comment by clesaege** [comment]
They could just set up a fake account to get all the bonus themselves and we already stated there were no referral in the T&C of the sale.

You are right participants are not incentivized to promote the project during a round of IICO.
But as soon as the round is over, they'll have incentive to do so and the project can benefit from that due to tokens having a higher price in the subsequent rounds.

**Comment by stefek99** [comment]
We could have a special `default` value or `EFF` referral field - so even if you don't know anyone who has recommended you, there is 1% or 2% bonus.

The bonus anyway is to incentivize the referral programme - so that those who haven't been referred are not in a worse position.

(I'm core supporter, biggest fan - I'm the first one to know and me getting penalized for not being referred is not fair)

About the incentives after the IICO - yeah, that is true... Me trying to find balance, so that incentives are aligned - otherwise cannot act with full commitment and integrity.
