### ISSUE TITLE
When now = endFullBonusTime, refund will be 0, if partialWidthdrawalLength is 0

### ISSUE THREAD

**Issue by 0xferit** [kleros/openiico-contract#36]
https://github.com/kleros/openiico-contract/blob/534b9acb4227a20c478b4b45bb15e339a97d5404/contracts/IICO.sol#L188

**Comment by 0xferit** [comment]
No, it's OK. There will be division by zero exception so it will revert.

**Comment by epiqueras** [comment]
If `partialWidthdrawalLength === 0`, then `endFullBonusTime === withdrawalLockTime`.

So this line:
https://github.com/kleros/openiico-contract/blob/534b9acb4227a20c478b4b45bb15e339a97d5404/contracts/IICO.sol#L182

Implies `now !== endFullBonusTime`.

There won't be a division by zero.

**Comment by 0xferit** [comment]
Yeah, before division by zero there is also that, right.
