### ISSUE TITLE
Make more tests

### ISSUE THREAD

**Issue by clesaege** [kleros/openiico-contract#6]
Make additional tests for this contract.
Duplicating tests is good.
Test all the specific settings which would come to your mind.
Test with a high amount of bids.

**Comment by stefek99** [comment]
It's easy to get started, some tests already exists: https://github.com/kleros/openiico-contract/blob/master/test/IICO.js

**Comment by clesaege** [comment]
Yeah, I tested all the usecases which came to my mind, but you can add more.
Also don't be afraid of testing again things which are already tested as automatic tests are the only place where doing redundant stuff is a good thing.

**Comment by clesaege** [comment]
We also need tests for the LevelWhitelisIICO contract.

**Comment by clesaege** [comment]
Done, thanks @stefek99
